vim.opt.softtabstop= 4
vim.opt.shiftwidth= 4
vim.opt.tabstop= 4
vim.opt.expandtab = true
vim.opt.relativenumber = true
vim.opt.nu =true
vim.opt.hlsearch = false
vim.opt.incsearch = true
vim.opt.hidden = true
vim.opt.termguicolors = true
vim.opt.wrap = false
vim.opt.scrolloff= 8
vim.opt.signcolumn='yes'
vim.opt.colorcolumn= '80'
vim.opt.shiftwidth= 4
vim.opt.backspace= 'indent,eol,start'
